### ISSUE TITLE
Allow omitting `MinSize` in disk customizations

### ISSUE THREAD

**Issue by supakeen** [osbuild/images#1301]
Currently the disk customizations require the `MinSize` field. I propose that omitting the field sets it to `0` so the following blueprint works:

```toml
[[customizations.disk.partitions]]
type = "lvm"
```

As opposed to having to write:

```toml
[[customizations.disk.partitions]]
type = "lvm"
minsize = 0
```
