### ISSUE TITLE
Allow omitting subvolumes for btrfs

### ISSUE THREAD

**Issue by supakeen** [osbuild/images#1302]
Currently when changing the disk partitioning for btrfs one has to provide (at least one) subvolumes:

```toml
[[customizations.disk.partitions]]
type = "btrfs"
minsize = "3 GiB"
subvolumes = [
  { name = "root", mountpoint = "/" },
]
```

When using the LVM type, it is not necessary to to pass anything else as we automatically do the right thing and create the groups as necessary.

```toml
[[customizations.disk.partitions]]
type = "lvm"
minsize = "3 GiB"
```

I propose doing the same for btrfs where a missing subvolumes gives a default subvolume configuration.
