### ISSUE TITLE
Change config-map to be an array

### ISSUE THREAD

**Issue by achilleas-k** [osbuild/images#1345]
I'd like to change the `config-map` format so that it's not keyed by filename.  There are cases where we want to define combinations of filters that require defining the same file twice, for example, it's impossible now to do the following:
```yaml
all-customizations:
  arches: ["x86_64"]
  distros: ["rhel-9*"]

all-customizations:
  distros: ["fedora-*"]
```
to use the same config to build all arches for Fedora but only x86_64 for RHEL 9.

Changing the format to an array with an extra field would work:
```yaml
- config_path: ./all-customizations.json
  arches: ["x86_64"]
  distros: ["rhel-9*"]
- config_path: ./all-customizations.json
  distros: ["fedora-*"]
```
